// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "go.opendefense.cloud/kit/example/client-go/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Bars returns a BarInformer.
	Bars() TypedBarInformer
	// ClusterBars returns a ClusterBarInformer.
	ClusterBars() TypedClusterBarInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Bars returns a TypedBarInformer.
func (v *version) Bars() TypedBarInformer {
	return &barInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ClusterBars returns a TypedClusterBarInformer.
func (v *version) ClusterBars() TypedClusterBarInformer {
	return &clusterBarInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
