//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	foo "go.opendefense.cloud/kit/example/api/foo"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Bar)(nil), (*foo.Bar)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Bar_To_foo_Bar(a.(*Bar), b.(*foo.Bar), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*foo.Bar)(nil), (*Bar)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_foo_Bar_To_v1alpha1_Bar(a.(*foo.Bar), b.(*Bar), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BarList)(nil), (*foo.BarList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BarList_To_foo_BarList(a.(*BarList), b.(*foo.BarList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*foo.BarList)(nil), (*BarList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_foo_BarList_To_v1alpha1_BarList(a.(*foo.BarList), b.(*BarList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BarSpec)(nil), (*foo.BarSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BarSpec_To_foo_BarSpec(a.(*BarSpec), b.(*foo.BarSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*foo.BarSpec)(nil), (*BarSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_foo_BarSpec_To_v1alpha1_BarSpec(a.(*foo.BarSpec), b.(*BarSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BarStatus)(nil), (*foo.BarStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BarStatus_To_foo_BarStatus(a.(*BarStatus), b.(*foo.BarStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*foo.BarStatus)(nil), (*BarStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_foo_BarStatus_To_v1alpha1_BarStatus(a.(*foo.BarStatus), b.(*BarStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterBar)(nil), (*foo.ClusterBar)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterBar_To_foo_ClusterBar(a.(*ClusterBar), b.(*foo.ClusterBar), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*foo.ClusterBar)(nil), (*ClusterBar)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_foo_ClusterBar_To_v1alpha1_ClusterBar(a.(*foo.ClusterBar), b.(*ClusterBar), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterBarList)(nil), (*foo.ClusterBarList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterBarList_To_foo_ClusterBarList(a.(*ClusterBarList), b.(*foo.ClusterBarList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*foo.ClusterBarList)(nil), (*ClusterBarList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_foo_ClusterBarList_To_v1alpha1_ClusterBarList(a.(*foo.ClusterBarList), b.(*ClusterBarList), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Bar_To_foo_Bar(in *Bar, out *foo.Bar, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_BarSpec_To_foo_BarSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_BarStatus_To_foo_BarStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Bar_To_foo_Bar is an autogenerated conversion function.
func Convert_v1alpha1_Bar_To_foo_Bar(in *Bar, out *foo.Bar, s conversion.Scope) error {
	return autoConvert_v1alpha1_Bar_To_foo_Bar(in, out, s)
}

func autoConvert_foo_Bar_To_v1alpha1_Bar(in *foo.Bar, out *Bar, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_foo_BarSpec_To_v1alpha1_BarSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_foo_BarStatus_To_v1alpha1_BarStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_foo_Bar_To_v1alpha1_Bar is an autogenerated conversion function.
func Convert_foo_Bar_To_v1alpha1_Bar(in *foo.Bar, out *Bar, s conversion.Scope) error {
	return autoConvert_foo_Bar_To_v1alpha1_Bar(in, out, s)
}

func autoConvert_v1alpha1_BarList_To_foo_BarList(in *BarList, out *foo.BarList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]foo.Bar)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_BarList_To_foo_BarList is an autogenerated conversion function.
func Convert_v1alpha1_BarList_To_foo_BarList(in *BarList, out *foo.BarList, s conversion.Scope) error {
	return autoConvert_v1alpha1_BarList_To_foo_BarList(in, out, s)
}

func autoConvert_foo_BarList_To_v1alpha1_BarList(in *foo.BarList, out *BarList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Bar)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_foo_BarList_To_v1alpha1_BarList is an autogenerated conversion function.
func Convert_foo_BarList_To_v1alpha1_BarList(in *foo.BarList, out *BarList, s conversion.Scope) error {
	return autoConvert_foo_BarList_To_v1alpha1_BarList(in, out, s)
}

func autoConvert_v1alpha1_BarSpec_To_foo_BarSpec(in *BarSpec, out *foo.BarSpec, s conversion.Scope) error {
	*out = *(*foo.BarSpec)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_BarSpec_To_foo_BarSpec is an autogenerated conversion function.
func Convert_v1alpha1_BarSpec_To_foo_BarSpec(in *BarSpec, out *foo.BarSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_BarSpec_To_foo_BarSpec(in, out, s)
}

func autoConvert_foo_BarSpec_To_v1alpha1_BarSpec(in *foo.BarSpec, out *BarSpec, s conversion.Scope) error {
	*out = *(*BarSpec)(unsafe.Pointer(in))
	return nil
}

// Convert_foo_BarSpec_To_v1alpha1_BarSpec is an autogenerated conversion function.
func Convert_foo_BarSpec_To_v1alpha1_BarSpec(in *foo.BarSpec, out *BarSpec, s conversion.Scope) error {
	return autoConvert_foo_BarSpec_To_v1alpha1_BarSpec(in, out, s)
}

func autoConvert_v1alpha1_BarStatus_To_foo_BarStatus(in *BarStatus, out *foo.BarStatus, s conversion.Scope) error {
	*out = *(*foo.BarStatus)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_BarStatus_To_foo_BarStatus is an autogenerated conversion function.
func Convert_v1alpha1_BarStatus_To_foo_BarStatus(in *BarStatus, out *foo.BarStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_BarStatus_To_foo_BarStatus(in, out, s)
}

func autoConvert_foo_BarStatus_To_v1alpha1_BarStatus(in *foo.BarStatus, out *BarStatus, s conversion.Scope) error {
	*out = *(*BarStatus)(unsafe.Pointer(in))
	return nil
}

// Convert_foo_BarStatus_To_v1alpha1_BarStatus is an autogenerated conversion function.
func Convert_foo_BarStatus_To_v1alpha1_BarStatus(in *foo.BarStatus, out *BarStatus, s conversion.Scope) error {
	return autoConvert_foo_BarStatus_To_v1alpha1_BarStatus(in, out, s)
}

func autoConvert_v1alpha1_ClusterBar_To_foo_ClusterBar(in *ClusterBar, out *foo.ClusterBar, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_BarSpec_To_foo_BarSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_BarStatus_To_foo_BarStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ClusterBar_To_foo_ClusterBar is an autogenerated conversion function.
func Convert_v1alpha1_ClusterBar_To_foo_ClusterBar(in *ClusterBar, out *foo.ClusterBar, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterBar_To_foo_ClusterBar(in, out, s)
}

func autoConvert_foo_ClusterBar_To_v1alpha1_ClusterBar(in *foo.ClusterBar, out *ClusterBar, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_foo_BarSpec_To_v1alpha1_BarSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_foo_BarStatus_To_v1alpha1_BarStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_foo_ClusterBar_To_v1alpha1_ClusterBar is an autogenerated conversion function.
func Convert_foo_ClusterBar_To_v1alpha1_ClusterBar(in *foo.ClusterBar, out *ClusterBar, s conversion.Scope) error {
	return autoConvert_foo_ClusterBar_To_v1alpha1_ClusterBar(in, out, s)
}

func autoConvert_v1alpha1_ClusterBarList_To_foo_ClusterBarList(in *ClusterBarList, out *foo.ClusterBarList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]foo.ClusterBar)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ClusterBarList_To_foo_ClusterBarList is an autogenerated conversion function.
func Convert_v1alpha1_ClusterBarList_To_foo_ClusterBarList(in *ClusterBarList, out *foo.ClusterBarList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterBarList_To_foo_ClusterBarList(in, out, s)
}

func autoConvert_foo_ClusterBarList_To_v1alpha1_ClusterBarList(in *foo.ClusterBarList, out *ClusterBarList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ClusterBar)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_foo_ClusterBarList_To_v1alpha1_ClusterBarList is an autogenerated conversion function.
func Convert_foo_ClusterBarList_To_v1alpha1_ClusterBarList(in *foo.ClusterBarList, out *ClusterBarList, s conversion.Scope) error {
	return autoConvert_foo_ClusterBarList_To_v1alpha1_ClusterBarList(in, out, s)
}
