name: Codegen Check
permissions:
  contents: read

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - id: go-version
        uses: opendefensecloud/dev-kit/.github/actions/get-go-version@ee5da7d94ff38d2e9fa54013be970a417ccb1340 # v2.0.0
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version: ${{ steps.go-version.outputs.version }}
      - name: Run codegen
        run: |
          cd example && make codegen
      - name: Check for changes
        uses: opendefensecloud/dev-kit/.github/actions/diff-check@ee5da7d94ff38d2e9fa54013be970a417ccb1340 # v2.0.0
