name: Golang CI

permissions:
  contents: read

on:
  push:
    branches: [main, develop]
    paths:
      - "**/*.go"
      - ".github/workflows/golang.yaml"
      - ".golangci.yml"
      - "Makefile"
      - "devenv.nix"
      - "go.mod"
      - "go.sum"
  pull_request:
    branches: [main, develop]
    paths:
      - "**/*.go"
      - ".github/workflows/golang.yaml"
      - ".golangci.yml"
      - "Makefile"
      - "devenv.nix"
      - "go.mod"
      - "go.sum"

env:
  GO_MODULE: https://github.com/opendefensecloud/apiserver-kit

jobs:
  lint:
    runs-on: ubuntu-24.04
    outputs:
      go-version: ${{ steps.go-version.outputs.version }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - id: go-version
        uses: opendefensecloud/dev-kit/.github/actions/get-go-version@ee5da7d94ff38d2e9fa54013be970a417ccb1340 # v2.0.0
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version: ${{ steps.go-version.outputs.version }}
      - name: lint-license-and-shell
        run: |
          make lint-no-golangci
      - name: golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9
        with:
          verify: false

  test:
    needs: lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version: ${{ needs.lint.outputs.go-version }}
      - name: test
        run: |
          make test
      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@e4612787670fc5b5f49026b8c29c5569921de1db # v1.2.0
        with:
          infile: sl.coverprofile
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@8d6379e14d29928660c4ba802d8e85393440b329 # v2.3.8
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov
